import Card from '../components/ui/Card';
import StatCard from '../components/ui/StatCard';
import LineChart from '../components/charts/LineChart';
import DonutChart from '../components/charts/DonutChart';
import './dashboard.css';

const MOCK = {
  stats: { monthlyAnalyses: 128, vulnerabilitiesFound: 342, avgImprovementRate: 34, autoGeneratedPRs: 47 },
  qualityTrend: [
    { label: '1월', value: 62 },
    { label: '2월', value: 58 },
    { label: '3월', value: 65 },
    { label: '4월', value: 70 },
    { label: '5월', value: 68 },
    { label: '6월', value: 75 },
    { label: '7월', value: 80 },
  ],
  issueDistribution: [
    { type: '보안', count: 142 },
    { type: '비효율', count: 96 },
    { type: '이슈', count: 78 },
    { type: '스타일', count: 26 },
  ],
};

export default function DashboardPage() {
  const { stats, qualityTrend, issueDistribution } = MOCK;

  return (
    <>
      <div className="gr-page__header">
        <div className="gr-page__header-text">
          <h1 className="text-display-md">HOME</h1>
          <span className="text-body-sm">조직 전체의 이번 달 코드 분석 현황입니다.</span>
        </div>
      </div>

      <div className="stat-grid">
        <StatCard icon="code" label="이번달 분석 건수" value={`${stats.monthlyAnalyses}건`} delta="+12%" />
        <StatCard icon="bug" label="발견된 취약점" value={`${stats.vulnerabilitiesFound}건`} delta="-8%" deltaDirection="down" />
        <StatCard icon="spark" label="평균 개선율" value={`${stats.avgImprovementRate}%`} delta="+5%p" />
        <StatCard icon="pr" label="자동 생성 PR" value={`${stats.autoGeneratedPRs}건`} delta="+9%" />
      </div>

      <div className="chart-grid">
        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">코드 품질 추이</h2>
            <span className="text-caption-md">최근 7개월 평균 품질 점수</span>
          </div>
          <LineChart data={qualityTrend} valueSuffix="점" />
        </Card>

        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">이슈 유형 분포</h2>
          </div>
          <DonutChart data={issueDistribution} />
        </Card>
      </div>
    </>
  );
}
