import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import Card from '../components/ui/Card';
import StatCard from '../components/ui/StatCard';
import LineChart from '../components/charts/LineChart';
import DonutChart from '../components/charts/DonutChart';
import './dashboard.css';

export default function DashboardPage() {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    api
      .get('/dashboard')
      .then(setData)
      .catch((err) => setError(err.message));
  }, []);

  if (error) return <div className="ui-banner ui-banner--error">{error}</div>;
  if (!data) return <div className="text-body-sm">불러오는 중…</div>;

  const { stats, qualityTrend, issueDistribution } = data;

  return (
    <>
      <div className="gr-page__header">
        <div className="gr-page__header-text">
          <h1 className="text-display-md">HOME</h1>
          <span className="text-body-sm">조직 전체의 이번 달 코드 분석 현황입니다.</span>
        </div>
      </div>

      <div className="stat-grid">
        <StatCard icon="code" label="이번달 분석 건수" value={`${stats.monthlyAnalyses}건`} delta="+12%" />
        <StatCard icon="bug" label="발견된 취약점" value={`${stats.vulnerabilitiesFound}건`} delta="-8%" deltaDirection="down" />
        <StatCard icon="spark" label="평균 개선율" value={`${stats.avgImprovementRate}%`} delta="+5%p" />
        <StatCard icon="pr" label="자동 생성 PR" value={`${stats.autoGeneratedPRs}건`} delta="+9%" />
      </div>

      <div className="chart-grid">
        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">코드 품질 추이</h2>
            <span className="text-caption-md">최근 7개월 평균 품질 점수</span>
          </div>
          <LineChart data={qualityTrend} valueSuffix="점" />
        </Card>

        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">이슈 유형 분포</h2>
          </div>
          <DonutChart data={issueDistribution} />
        </Card>
      </div>
    </>
  );
}
