import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import Card from '../components/ui/Card';
import StatCard from '../components/ui/StatCard';
import LineChart from '../components/charts/LineChart';
import DonutChart from '../components/charts/DonutChart';
import Icon from '../components/icons/Icon';
import './dashboard.css';

export default function MySpacePage() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!user) return;
    api
      .get(`/myspace?userId=${user.id}`)
      .then((rows) => setData(rows[0] || null))
      .catch((err) => setError(err.message));
  }, [user]);

  if (error) return <div className="ui-banner ui-banner--error">{error}</div>;
  if (!data) return <div className="text-body-sm">불러오는 중…</div>;

  const { stats, qualityTrend, issueDistribution, styleSummary } = data;

  return (
    <>
      <div className="gr-page__header">
        <div className="gr-page__header-text">
          <h1 className="text-display-md">My Space</h1>
          <span className="text-body-sm">{user.name}님의 GitHub PR 기준 코드 품질 현황입니다.</span>
        </div>
      </div>

      <div className="stat-grid">
        <StatCard icon="pr" label="이번달 PR 건수" value={`${stats.monthlyPRs}건`} delta="+3건" />
        <StatCard icon="bug" label="수정한 취약점" value={`${stats.vulnerabilitiesFixed}건`} delta="+6건" />
        <StatCard icon="spark" label="평균 개선율" value={`${stats.avgImprovementRate}%`} delta="+7%p" />
        <StatCard icon="code" label="자동 생성 PR" value={`${stats.autoGeneratedPRs}건`} delta="+2건" />
      </div>

      <div className="chart-grid">
        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">코드 품질 추이</h2>
            <span className="text-caption-md">내 PR 기준 · 최근 7개월</span>
          </div>
          <LineChart data={qualityTrend} valueSuffix="점" />
        </Card>

        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">이슈 유형 분포</h2>
          </div>
          <DonutChart data={issueDistribution} />
        </Card>
      </div>

      <Card className="style-summary">
        <div className="chart-card__header">
          <h2 className="text-heading-md" style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <Icon name="spark" size={16} /> AI 코딩 스타일 요약
          </h2>
        </div>
        <p className="style-summary__body text-body-md">{styleSummary}</p>
      </Card>
    </>
  );
}
