import { useAuth } from '../context/AuthContext';
import Card from '../components/ui/Card';
import StatCard from '../components/ui/StatCard';
import LineChart from '../components/charts/LineChart';
import DonutChart from '../components/charts/DonutChart';
import Icon from '../components/icons/Icon';
import './dashboard.css';

const MOCK = {
  stats: { monthlyPRs: 14, vulnerabilitiesFixed: 38, avgImprovementRate: 41, autoGeneratedPRs: 5 },
  qualityTrend: [
    { label: '1월', value: 58 },
    { label: '2월', value: 63 },
    { label: '3월', value: 60 },
    { label: '4월', value: 67 },
    { label: '5월', value: 72 },
    { label: '6월', value: 69 },
    { label: '7월', value: 78 },
  ],
  issueDistribution: [
    { type: '보안', count: 18 },
    { type: '비효율', count: 11 },
    { type: '이슈', count: 7 },
    { type: '스타일', count: 2 },
  ],
  styleSummary: '전반적으로 함수 단위 분리가 잘 되어 있으며, 변수명 명확성이 높습니다. 반복 패턴에서 유틸 함수 추출을 고려해보세요.',
};

export default function MySpacePage() {
  const { user } = useAuth();
  const { stats, qualityTrend, issueDistribution, styleSummary } = MOCK;

  return (
    <>
      <div className="gr-page__header">
        <div className="gr-page__header-text">
          <h1 className="text-display-md">My Space</h1>
          <span className="text-body-sm">{user.name}님의 GitHub PR 기준 코드 품질 현황입니다.</span>
        </div>
      </div>

      <div className="stat-grid">
        <StatCard icon="pr" label="이번달 PR 건수" value={`${stats.monthlyPRs}건`} delta="+3건" />
        <StatCard icon="bug" label="수정한 취약점" value={`${stats.vulnerabilitiesFixed}건`} delta="+6건" />
        <StatCard icon="spark" label="평균 개선율" value={`${stats.avgImprovementRate}%`} delta="+7%p" />
        <StatCard icon="code" label="자동 생성 PR" value={`${stats.autoGeneratedPRs}건`} delta="+2건" />
      </div>

      <div className="chart-grid">
        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">코드 품질 추이</h2>
            <span className="text-caption-md">내 PR 기준 · 최근 7개월</span>
          </div>
          <LineChart data={qualityTrend} valueSuffix="점" />
        </Card>

        <Card className="chart-card">
          <div className="chart-card__header">
            <h2 className="text-heading-md">이슈 유형 분포</h2>
          </div>
          <DonutChart data={issueDistribution} />
        </Card>
      </div>

      <Card className="style-summary">
        <div className="chart-card__header">
          <h2 className="text-heading-md" style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <Icon name="spark" size={16} /> AI 코딩 스타일 요약
          </h2>
        </div>
        <p className="style-summary__body text-body-md">{styleSummary}</p>
      </Card>
    </>
  );
}
